services:
  netdata:
    image: netdata/netdata:v2.8.4
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    volumes:
      # Mounts for persistence
      - /opt/netdata/config:/etc/netdata
      - /opt/netdata/lib:/var/lib/netdata
      - /opt/netdata/cache:/var/cache/netdata

      # Mounts for host monitoring
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 19999:19999
    deploy:
      mode: global
