---
services:
  sponsorblock:
    image: ghcr.io/dmunozv04/isponsorblocktv@sha256:545856523283753ebcf4b400a46895b9906844be5265a0f4cab98a6b0bdf84be
    volumes:
      - "/mnt/cephfs/sponsorblock:/app/data"

networks:
  default:
    external: true
    name: main
