services:
  gitea:
    image: docker.gitea.com/gitea:1.25
    environment:
      - USER_UID=${PUID?error}
      - USER_GID=${PGID?error}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - "/mnt/cephfs/gitea-config:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - db

  db:
    image: postgres:18.2
    user: "${PUID?error}:${PGID?error}"
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - "/mnt/cephfs/gitea-db:/var/lib/postgresql"

networks:
  default:
    external: true
    name: main
